site_url: https://redlink.netlify.app/
logo_url: https://redlink.netlify.app/iconOnlyR.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
  repo: redlink-gmbh/redlink-website
  squash_merges: true

media_folder: static/img
public_folder: /img

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_files

  # Required - a list of locales to show in the editor UI
  locales: [de, en]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: de

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: "Site settings"
    name: "site"
    files:
      - label: "Info"
        name: "info"
        file: "content/site/info.json"
        format: "json"
        i18n: true
        editor:
          preview: false
        fields:
          - {
              label: Site Name,
              name: sitename,
              widget: string,
              hint: "This is used for the site title",
            }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: "This is used as descriptive text for links that link to this site",
            }
          - {
            label: Site main mail address,
            name: siteMailAddress,
            widget: string,
            hint: "This is used for contacting you via mail",
          }
          - {
            label: Site main phone number,
            name: sitePhoneNumber,
            widget: string,
            hint: "This is used for contacting you via phone",
          }
          - { label: "Body", name: "siteStartBody", widget: "markdown", required: false, i18n: true }
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    i18n: true
    create: true
    format: "frontmatter"
    slug: "blog/{{slug}}"
    # editor:
    #   preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true, i18n: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true,
          required: false,
        }
      - { label: "Content", name: "body", widget: "markdown", required: false, i18n: true }
  - name: "team"
    i18n: true
    label: "Grape varieties"
    label_singular: "Project"
    folder: "content/team"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    preview_path: "team/{{slug}}"
    fields:
      - {
        label: "Title",
        name: "name",
        widget: "string",
        i18n: true,
        required: true,
      }
      - {
        label: "Description",
        name: "role",
        widget: "string",
        i18n: true,
        required: false,
      }
      - {
        label: "Cover Image",
        name: "imageUrl",
        widget: "image",
        required: false,
        i18n: true,
        allow_multiple: false,
      }
      - {
        label: "Description",
        name: "twitterUrl",
        widget: "string",
        i18n: true,
        required: false,
      }
      - {
        label: "Description",
        name: "linkedinUrl",
        widget: "string",
        i18n: true,
        required: false,
      }
  - name: "jobs"
    label: "Jobs"
    folder: "content/jobs"
    i18n: true
    create: true
    format: "frontmatter"
    slug: "jobs/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true, i18n: true }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        i18n: true,
        required: false,
      }
      - { label: "Content", name: "body", widget: "markdown", required: false, i18n: true }
